In [7]:
import xarray as xr
import numpy as np
import pandas as pd

In [8]:
mas1 = [2, 6]
mas2 = [0, 4, 8]
coord1 = [1, 3]
coord2 = [0, 2, 4]

In [9]:
da1 = xr.DataArray(mas1,{'x': coord1})
da2 = xr.DataArray(mas2, {'x': coord2})

In [10]:
ds = xr.Dataset({'d1':da1,'d2':da2})

In [11]:
np.array(3).item()

3

In [12]:
coord = {'x': [2,8,10], 'y': [1,3,4]}

In [13]:
ar1 = xr.DataArray(np.zeros([3,3]),coord, name='wew')

In [14]:
ar2 = xr.DataArray()

In [15]:
ds = xr.Dataset({'is': ar1, 'val': ar2})

In [16]:
ds['is'].sel({'x': 8}, method='ffill')

<xarray.DataArray 'is' (y: 3)>
array([0., 0., 0.])
Coordinates:
    x        int64 8
  * y        (y) int64 1 3 4

In [17]:
p = ds['is'].sel(x=8, y=1)

In [18]:
p['x']

<xarray.DataArray 'x' ()>
array(8)
Coordinates:
    x        int64 8
    y        int64 1

In [19]:
p.coords.values()

ValuesView(Coordinates:
    x        int64 8
    y        int64 1)

In [43]:
a0 = xr.DataArray(8,{'x': 2, 'y': 3}, name='qqq')
a1 = xr.DataArray([[1,2],[3,4]],{'x':[4,5],'y':[5,7]}, name='qqq')

In [44]:
a0

<xarray.DataArray 'qqq' ()>
array(8)
Coordinates:
    x        int64 2
    y        int64 3

In [45]:
a1.combine_first(a0)


<xarray.DataArray 'qqq' (x: 2, y: 2)>
array([[1, 2],
       [3, 4]])
Coordinates:
  * x        (x) int64 4 5
  * y        (y) int64 5 7

In [108]:
ar0 = xr.DataArray([[0, 1], [2, 3]], [("x", [1, 2]), ("y", [-1, 0])])
p = ar0.sel(x=[1], y=[-1], method='nearest')

In [109]:
ar0

<xarray.DataArray (x: 2, y: 2)>
array([[0, 1],
       [2, 3]])
Coordinates:
  * x        (x) int64 1 2
  * y        (y) int64 -1 0

In [112]:
p.data[0,0] = 8

In [115]:
a = 3

In [121]:
a = np.array([1,2,3,5])

In [190]:
ar1 = xr.DataArray(np.ones([1, 1])*8, {'x': [1], 'y': [0]})
ar0 = xr.DataArray([[0, np.nan], [-10, 2]], [("x", [1, 2]), ("y", [-1, 0])])

In [209]:
ar0.max().data

array(2.)

In [253]:
arf = xr.DataArray([0,2,6,3,np.nan,-1],{'x': [0,1,2,3,4,5]})

In [256]:
arf

<xarray.DataArray (x: 6)>
array([ 0.,  2.,  6.,  3., nan, -1.])
Coordinates:
  * x        (x) int64 0 1 2 3 4 5

In [269]:
a, b = np.array([1,5])

In [277]:
for x, y in a, b:
    print(x)
    print(y)

1
3
3
6


In [276]:
b = 3,6

In [257]:
a = np.nan

In [259]:
type(a)

float

In [265]:
arf

<xarray.DataArray (x: 6)>
array([ 0.,  2.,  6.,  3., nan, -1.])
Coordinates:
  * x        (x) int64 0 1 2 3 4 5

In [264]:
arf.dropna('x')

<xarray.DataArray (x: 5)>
array([ 0.,  2.,  6.,  3., -1.])
Coordinates:
  * x        (x) int64 0 1 2 3 5

In [227]:
ar0.x.sel(x=[1,1])

<xarray.DataArray 'x' (x: 2)>
array([1, 1])
Coordinates:
  * x        (x) int64 1 1

In [229]:
yd = xr.DataArray([0,0],{'border':['up','down']})

In [232]:
brd = arf * yd

In [242]:
brd[{'x': 2}] = [1,2]

In [247]:
brd.x[0]

<xarray.DataArray 'x' ()>
array(0)
Coordinates:
    x        int64 0

In [181]:
ar0.interp(x=[1.5], y=[-0.5], method='linear', kwargs={'bounds_error': False, 'fill_value': -100})


<xarray.DataArray (x: 1, y: 1)>
array([[-4.5]])
Coordinates:
  * x        (x) float64 1.5
  * y        (y) float64 -0.5

In [133]:
ar0.name = 'qqq'
ar1.name = 'qqq'

In [137]:
xr.c([ar1, ar0])


TypeError: concat() missing 1 required positional argument: 'dim'

In [122]:
np.array(a).flatten()

array([1, 2, 3, 5])

In [99]:
p2 = ar0[:,1]

In [105]:
p2.data[0] = 8

In [113]:
ar0

<xarray.DataArray (x: 2, y: 2)>
array([[0, 1],
       [2, 3]])
Coordinates:
  * x        (x) int64 1 2
  * y        (y) int64 -1 0

In [81]:
p1

<xarray.DataArray (x: 1, y: 1)>
array([[1.]])
Coordinates:
  * x        (x) <U1 'a'
  * y        (y) int64 0

In [72]:
ar1 = xr.DataArray(np.ones([1,1]),{'x':['a'],'y': [0]})

In [144]:
a = np.ones([1,1])
for i in np.nditer(a):
    print(i)

1.0


In [73]:
ar1

<xarray.DataArray (x: 1, y: 1)>
array([[1.]])
Coordinates:
  * x        (x) <U1 'a'
  * y        (y) int64 0

In [83]:
ar0 = xr.DataArray([[0, 1], [2, 3]], [("x", [1, 2]), ("y", [-1, 0])])

# ar1 = xr.DataArray([[1], [1]], {"x": "b", "y": [0, 1]})

# ar0.combine_first(ar1)

# ar1.combine_first(ar0)

In [28]:
xr.merge([a1, a0], compat='override')


<xarray.Dataset>
Dimensions:  (x: 2, y: 2)
Coordinates:
  * x        (x) int64 4 5
  * y        (y) int64 5 7
Data variables:
    qqq      (x, y) int64 1 2 3 4

In [31]:
a=np.nan

In [37]:
a1

<xarray.DataArray 'qqq' ()>
array(nan)
Coordinates:
    x        int64 4
    y        int64 5

In [47]:
type(a1.item())

float

In [51]:
if np.isnan(a1):
    print('rere')

rere


In [48]:
a1.item() == float('nan')

False

In [30]:
xr.merge(a1, a1)

TypeError: iteration over a 0-d array

In [124]:
ar1.get_index('x')

Int64Index([2, 8, 10], dtype='int64', name='x')

In [135]:
ar1.max().item()

0.0

In [106]:
a1 = xr.DataArray(1, coords={'x': 2, 'y': 3}, name='qqq')


In [107]:
ds = xr.Dataset({'q': a1, 'w':ar1})

In [1]:
xr.merge(a0, a1)

NameError: name 'xr' is not defined

In [83]:
mg = xr.merge([a0,a1])

In [65]:
xr.where((ar1.coords.values == p.coords.all()), 100, ar1)

AttributeError: 'DataArrayCoordinates' object has no attribute 'all'

In [60]:
xr.where((ar1.coords["x"] == 8) & (ar1.coords["y"] == 1), 100, ar1)

<xarray.DataArray (x: 3, y: 3)>
array([[  0.,   0.,   0.],
       [100.,   0.,   0.],
       [  0.,   0.,   0.]])
Coordinates:
  * x        (x) int64 2 8 10
  * y        (y) int64 1 3 4

In [52]:
ar1[{'x': 0, 'y': 1}]

<xarray.DataArray ()>
array(0.)
Coordinates:
    x        int64 2
    y        int64 3

In [21]:
ds['is'].sel(x=8, y=1) = 2

SyntaxError: cannot assign to function call here. Maybe you meant '==' instead of '='? (1091012767.py, line 1)

In [8]:
da1.x.sel(x=slice(0,-1)).data

array([], dtype=int64)

In [58]:
slice(1,4,2.3)

slice(1, 4, 2.3)

In [9]:
da1

<xarray.DataArray (x: 2)>
array([2, 6])
Coordinates:
  * x        (x) int64 1 3

In [25]:
da1.x.sel(x=1.5, method='ffill',drop=0.1)

<xarray.DataArray 'x' ()>
array(1)

In [7]:
import time

In [3]:
def f(x):
    print('in fun x:', x)

In [80]:
class out:
    def __init__(self) -> None:
        self.w = 26
    class iner():
        def __init__(self) -> None:
            print(self.w)

In [62]:
o = out

In [63]:
o.iner()

AttributeError: 'iner' object has no attribute 'w'

In [8]:
class longf():
    def __init__(self, n) -> None:
        self.n = n
        self.result = None
    def __call__(self):
        if self.result is None:
            time.sleep(2)
            self.result = 2 * self.n
        return self.result
        

In [9]:
m = [longf(x) for x in range(10)]

In [10]:
m

In [84]:
n = np.arange(10)
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
nas  = n.

In [87]:
[[i for i in range(6)] for j in range(5)]

[[0, 1, 2, 3, 4, 5],
 [0, 1, 2, 3, 4, 5],
 [0, 1, 2, 3, 4, 5],
 [0, 1, 2, 3, 4, 5],
 [0, 1, 2, 3, 4, 5]]

In [33]:
nas[0]

In [19]:
dat = xr.DataArray(nas, coords={'x': range(-5,5)})

In [90]:
for i in dat.x.data:
    print(i)

-5
-4
-3
-2
-1
0
1
2
3
4


In [60]:
dat.sel(x=-2).item()()

6

In [63]:
d3 = ds.sel(x=slice(-100,103.4)).mean('x')

In [100]:
d3 = da1.sel(x=slice(-100, 103.4)).mean('x', keepdims=True)


In [85]:
m = xr.DataArray(np.ones(5),coords={'y':range(5)})

In [102]:
da1

<xarray.DataArray (x: 2)>
array([2, 6])
Coordinates:
  * x        (x) int64 1 3

In [95]:
da1

<xarray.DataArray (x: 2)>
array([2, 6])
Coordinates:
  * x        (x) int64 1 3

In [110]:
sta = xr.concat([da1, 2 * da1, da1, 2 * da1, da1],'y')


In [112]:
sta.coords['y']=range(5)

In [116]:
sta

<xarray.DataArray (y: 5, x: 2)>
array([[ 2,  6],
       [ 4, 12],
       [ 2,  6],
       [ 4, 12],
       [ 2,  6]])
Coordinates:
  * x        (x) int64 1 3
  * y        (y) int64 0 1 2 3 4